version: "3.8"

services:
    server:
        build:
            context: ./
            dockerfile: Dockerfile
        image: ${DOCKER_IMAGE_NAME}
        restart: unless-stopped
        labels:
            - "io.portainer.accesscontrol.teams=esi"
        environment:
            - DOCKER_IMAGE_NAME
